Practical Task for Ensemble Algorithms

Practical Task: 
Complete these two questions given below using the “german_data_creditcard.csv” dataset. Please send the python code which you prepared to complete the tasks below with explanations of your results.
1.	Report the best hypermeters which used to run Random Forest algorithm. Explain your results.
2.	Run Adaboost and GB on the given data and compare. Explain your results.

RandomForestClassifier — scikit-learn 1.8.0 documentation
GradientBoostingClassifier — scikit-learn 1.8.0 documentation
AdaBoostClassifier — scikit-learn 1.8.0 documentation
GridSearchCV — scikit-learn 1.8.0 documentation
Note: You can take the help of given python code also go through the below reference link to understand the concept.
Bagging and boosting
https://analyticsindiamag.com/primer-ensemble-learning-bagging-sboosting/#:~:text=Bagging%20is%20a%20way%20to,based%20on%20the%20last%20classification.
A Primer to Ensemble Learning – Bagging and Boosting (analyticsindiamag.com)

1.	Report the best hypermeters which used to run Random Forest algorithm. Explain your results.

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df = pd.read_csv("german_data_creditcard.csv")

print(df.shape)
print(df.columns)

(1000, 16)
Index(['Creditability', 'Acc_Bal_bin', 'Pay_Status_bin', 'Value_SavStock_bin',
       'Length_Emp_bin', 'S&M_Status_bin', 'No_of_Credits_bin',
       'Co_Credits_bin', 'Purpose_bin', 'Telephone_bin', 'Instalment_bin',
       'Apartment_bin', 'Most_Val_Asset_bin', 'Duration_Credit',
       'Credit_Amount', 'Age_bin'],
      dtype='object')


In [10]:
#Split Features and Target
x = df.drop("Creditability", axis=1)
y = df["Creditability"]

x = pd.get_dummies(x, drop_first=True)

#Train-Test Split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42, stratify=y
)

In [11]:
#Random Forest
rf = RandomForestClassifier(random_state=42)

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5]
}

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    scoring="accuracy"
)

grid_search.fit(x_train, y_train)

print("Parameters:", grid_search.best_params_)
print("Accuracy:", grid_search.best_score_)

Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 100}
Accuracy: 0.7557142857142857


In [12]:
#Get best Random Forest
best_rf = grid_search.best_estimator_

y_pred_rf = best_rf.predict(x_test)

print("Random Forest Test Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Test Accuracy: 0.7533333333333333
[[ 35  55]
 [ 19 191]]
              precision    recall  f1-score   support

           0       0.65      0.39      0.49        90
           1       0.78      0.91      0.84       210

    accuracy                           0.75       300
   macro avg       0.71      0.65      0.66       300
weighted avg       0.74      0.75      0.73       300



Random Forest is a method that builds decision trees and combine them to make desition.It helps to maintain stability and reduce overfitting

GridSearchCV is find best one using cross validation

parameters ware tested
    n_estimator - number of trees
    max_depth - how deep trees can go
    min_samples_split, min_samples_leaf - to control overfitting

2.	Run Adaboost and GB on the given data and compare. Explain your results.

In [ ]:
#AdaBoost
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

ada = AdaBoostClassifier(random_state=42)
ada.fit(x_train, y_train)

y_pred_ada = ada.predict(x_test)

print("AdaBoost Accuracy:", accuracy_score(y_test, y_pred_ada))
print(confusion_matrix(y_test, y_pred_ada))
print(classification_report(y_test, y_pred_ada))

AdaBoost Accuracy: 0.7666666666666667
[[ 44  46]
 [ 24 186]]
              precision    recall  f1-score   support

           0       0.65      0.49      0.56        90
           1       0.80      0.89      0.84       210

    accuracy                           0.77       300
   macro avg       0.72      0.69      0.70       300
weighted avg       0.76      0.77      0.76       300



In [14]:
#Gradient Voosting
gb = GradientBoostingClassifier(random_state=42)
gb.fit(x_train, y_train)

y_pred_gb = gb.predict(x_test)

print("Gradient Accuracy:", accuracy_score(y_test, y_pred_gb))
print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

Gradient Accuracy: 0.7866666666666666
[[ 47  43]
 [ 21 189]]
              precision    recall  f1-score   support

           0       0.69      0.52      0.59        90
           1       0.81      0.90      0.86       210

    accuracy                           0.79       300
   macro avg       0.75      0.71      0.73       300
weighted avg       0.78      0.79      0.78       300



AdaBoost and Gradient ossting use as a Boosting methods. Build trees independently and boosting build models lika one ofter onother. New model tries to correct mistakes made by privious model.